version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgresql://username:password@db:5432/microblog"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npx prisma migrate deploy && npm run start:dev"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microblog
    ports:
      - 5432:5432 # enables connecting locally via psql
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
